config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  devise_for :users
  get 'about' => 'pages', as: 'about'
  root 'posts#index', as: 'home'
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  has_one_attached :avatar
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 4}
  validates :body, presence: true
  has_one_attached :image
  def next
    Post.where("id > ?", id).order("id ASC").first
  end

  def previous
    Post.where("id < ?", id).order("id DESC").first
  end
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end
  private def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def show
    @post= Post.find(params[:id])
  end

  def edit
    @post= Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(params[:post].permit(:title, :body, :image))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  def create
    @post = Post.new(post_params)
    if(@post.save)
    redirect_to @post
    else
      render 'new'
    end
  end
  private def post_params
    params.require(:post).permit(:title, :body, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="row">
  <div class="col">
    <p class="post_body"><strong><%= comment.username %></strong>: <%= comment.body %></p>
    <p class="post_date1"><%= time_ago_in_words(comment.created_at) %> ago</p>
  </div>
  <div class="col btn1">
    <% if user_signed_in? %>
      <p><%= link_to 'Удалить', [comment.post, comment], method: :delete, class: "btn btn-outline-dark",
                     data: {confirm: 'Удалить комментарий?'}, id: "btn1" %></p>
    <%end %>
  </div>
</div>
<hr>

app/views/comments/_form.html.erb
<h4 class="post_body">Добавить комментарий</h4>
<%= form_for ([@post, @post.comments.build]) do |f|%>
  <form>
    <div class="form-group">
      <label for="formGroupExampleInput" class="post_body">Имя пользователя</label>
      <%= f.text_field :username, {:class => 'form-control'} %>
    </div>
    <div class="form-group post_body">
      <label for="formGroupExampleInput2">Комментарий</label>
      <%= f.text_area :body, {:class => 'form-control'} %>
    </div>
    <p><%= f.submit("Сохранить",{:class => 'btn btn-outline-dark'})%></p>
  </form>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet"  href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script  type = " text / javascript "  src = " trix.js " > </script >
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<header>
  <nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container-xl">
      <a class="navbar-brand">BLOG ZLO</a>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample07XL" aria-controls="navbarsExample07XL" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse collapse" id="navbarsExample07XL">
        <ul class="navbar-nav mr-auto">
          <li>
            <a> <%= link_to "Главная страница", home_path, class: "nav-link" %></a>
          </li>
          <li>
            <a><%= link_to "Автор", about_path, class: "nav-link"%> </a>
          </li>
          <li>
            <a> <%= link_to "Новая статья", new_post_path, class: "nav-link"%></a>
          </li>
        </ul>
        <ul class="mt-3 md-3">
          <li><a href="https://github.com/HappyKate"><%= image_tag("icons8-github-48.png", :alt => "GITHUB", class: "icon") %></a></li>
          <li><a href="https://vk.com/id304033116"><%= image_tag("icons8-вконтакте-48.png", :alt => "VK", class: "icon") %></a></li>
          <li><a href="https://www.instagram.com/katerinka96.13/"><%= image_tag("icons8-instagram-48.png", :alt => "INST", class: "icon") %></a></li>
          <li><a href="mailto:zlaaayya@gmail.com"><%= image_tag("icons8-gmail-48.png", :alt => "GMAIL", class: "icon") %></a></li>
        </ul>
        <div class="actions">
          <%= link_to "Вход", user_session_path, class: 'btn btn-outline-light', id: 'sign_up' %>
        </div>
      </div>
    </div>
  </nav>
  <div class="container" id="head">
    <% if current_page?(home_path) %>
      <p>Все посты</p>
    <% elsif current_page?(about_path)%>
      <p>Автор</p>
    <%else %>
      <%= link_to"Вернуться ко всем постам", home_path, class: "head" %>
    <%end %>
  </div>
</header>

  <div class="container mt-4 md-4" id="content">
    <%= yield %>
  </div>
  <div class="footer mt-5 md-5">
    <div class="container" id="footer_size">
      <div class="footer_text">Разработка сайта - <a class="git" href="https://github.com/HappyKate">HappyKate</a>
      </div>
    </div>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="mt-5 md-5" id="about">
  <div class="col">
    <%=image_tag "4hoHcFDdECc.jpg", class: "media"%>
  </div>
  <div class="col-8">
    <h2 class="post_name1">Hey, I'm Katerina.</h2>
    <p class="post_body">Welcome to my Blog zlo.
      This blog was written in Ruby on Rails. </p>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f|%>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%=msg %></div>
    <%end %>
  <%end %>
  <form>

    <div class="form-group">
      <label for="formGroupExampleInput">Название статьи</label>
      <%= f.text_field :title, {:class => 'form-control'} %>
    </div>
    <div class="form-group ">
      <label for="formGroupExampleInput2">Статья</label>
      <%= f.text_area :body, {:class => 'form-control'} %>
    </div>
      <%= f.file_field :image, {:class => "input_file"}%>
    <p class="mt-3 md-3"><%= f.submit("Сохранить",{:class => 'btn btn-outline-dark'})%></p>
  </form>
<%end%>

app/views/posts/edit.html.erb
<h4>Редактировать пост</h4>
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="post_col">
  <% @posts.each do |post| %>
    <div class="col-md-6 mt-4 md-4">
      <div class="info_post  border shadow-sm">
        <div class="title-post">
          <h4><%=link_to post.title, post, class: "post_name" %></h4>
          <p class="post_date"><%= post.created_at.strftime("%d, %b, %Y")%></p>
        </div>
        <div id="image_post"><% if post.image.attached? %>
            <%= image_tag rails_blob_path(post.image, 'attachment'), class: 'img-fluid' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h2 class="new_post">Новый пост</h2>
<%= render 'form' %>

app/views/posts/show.html.erb
<h1 class="post_name1"><%= @post.title %></h1>
<p class="post_date1"><%= time_ago_in_words(@post.created_at) %> ago</p>

<p class="post_body"><%= raw @post.body %></p>
<div id="strela">
  <% if @post.next.present? %>
    <%= link_to @post.next do %>
      <%= image_tag "icons8-назад-50.png", class: "strela" %>
    <% end %>
  <% end %>

  <% if @post.previous.present? %>
    <%= link_to @post.previous do %>
      <%= image_tag "icons8-вперед-50.png", class: "strela" %>
    <% end %>
  <% end %>
</div>
<% if user_signed_in? %>
  <div class="knp">
    <%= link_to "Редактировать", edit_post_path(@post), :class => 'btn btn-outline-dark' %>
    <%= link_to "Удалить", post_path(@post), method: :delete, data: {confirm: 'Удалить статью?'}, :class => 'btn btn-outline-dark' %>
  </div>
<% end %>
<hr>
<h4 class="post_body"><%= @post.comments.count %> Comments</h4>
<div class="mt-3 md-3">
  <div class="container">
  <%= render @post.comments %>
  <% if user_signed_in? %>
    <%= render 'comments/form' %>
  <% end %>
  </div>
</div>